# 0. Install Dependencies and Bring in Data

In [2]:

#pip install tensorflow

In [3]:
#pip install tensorflow-gpu==2.12.0

In [4]:
#pip install opencv-python matplotlib

In [5]:
#pip install pandas

In [1]:

import os
import pandas as pd
import numpy as np
import tensorflow as tf



tf.config.threading.set_intra_op_parallelism_threads(os.cpu_count())
tf.config.threading.set_inter_op_parallelism_threads(os.cpu_count())


df = pd.read_csv(os.path.join('jigsaw-toxic-comment-classification-challenge','train.csv', 'train.csv'))



df.tail()


df.iloc[5]['comment_text']





'"\n\nCongratulations from me as well, use the tools well. \xa0· talk "'

In [2]:
df.head(10)

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   
5  00025465d4725e87  "\n\nCongratulations from me as well, use the ...      0   
6  0002bcb3da6cb337       COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK      1   
7  00031b1e95af7921  Your vandalism to the Matt Shirvington article...      0   
8  00037261f536c51d  Sorry if the word 'nonsense' was offensive to ...      0   
9  00040093b2687caa  alignment on this subject and which are contra...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0  
5             0        0       0       0              0  
6             1        1       0       1              0  
7             0        0       0       0              0  
8             0        0       0       0              0  
9             0        0       0       0              0

# 1. Preprocess

Tokenizing the data is translating the ssentences into our own secret language that only deep learning model understands converting each word in sentence into a unique identifire then we will create our training testing validaion

In [11]:
!pip list

Package                      Version
---------------------------- -----------
absl-py                      2.1.0
aiohappyeyeballs             2.4.4
aiohttp                      3.11.11
aiosignal                    1.3.2
asttokens                    3.0.0
astunparse                   1.6.3
async-timeout                5.0.1
attrs                        24.3.0
blinker                      1.9.0
Brotli                       1.1.0
cached-property              1.5.2
cachetools                   5.5.0
certifi                      2024.12.14
cffi                         1.17.1
charset-normalizer           3.4.0
click                        8.1.8
colorama                     0.4.6
comm                         0.2.2
contourpy                    1.3.0
cryptography                 39.0.0
cycler                       0.12.1
debugpy                      1.8.11
decorator                    5.1.1
exceptiongroup               1.2.2
executing                    2.1.0
flatbuffers                  24.3.2

In [3]:
from tensorflow.keras.layers import TextVectorization
# TextVectorization takes a word and convert it to code for example hey might be 42

In [4]:
df.columns

Index(['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate'],
      dtype='object')

In [5]:
df.columns[2:].values

array(['toxic', 'severe_toxic', 'obscene', 'threat', 'insult',
       'identity_hate'], dtype=object)

In [6]:
df[df.columns[2:]].values

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [7]:
X = df['comment_text']
y = df[df.columns[2:]].values

print(X)

print("===========================================")

print(y)

# split our data x is our comment text y is our features

0         Explanation\nWhy the edits made under my usern...
1         D'aww! He matches this background colour I'm s...
2         Hey man, I'm really not trying to edit war. It...
3         "\nMore\nI can't make any real suggestions on ...
4         You, sir, are my hero. Any chance you remember...
                                ...                        
159566    ":::::And for the second time of asking, when ...
159567    You should be ashamed of yourself \n\nThat is ...
159568    Spitzer \n\nUmm, theres no actual article for ...
159569    And it looks like it was actually you who put ...
159570    "\nAnd ... I really don't think you understand...
Name: comment_text, Length: 159571, dtype: object
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 ...
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [8]:
MAX_WORDS = 200000 # number of words in the vocab

In [9]:
vectorizer = TextVectorization(max_tokens=MAX_WORDS,
                               output_sequence_length=1800,
                               output_mode='int')

# If MAX_WORDS=1000, only the 1000 most common tokens from the dataset will be retained.
# All other tokens will be mapped to a special "[UNK]" (unknown) token.

# output_sequence_length=1800 Specifies the maximum length of the output sequence.

# int Converts each token into an integer corresponding to its index in the vocabulary.

In [10]:
vectorizer.adapt(X.values) 

# Purpose: This method allows the TextVectorization layer to analyze and learn the characteristics of the dataset.
# Specifically, it builds the vocabulary based on the text data in X.values.

In [11]:
vectorizer.get_vocabulary()

# Purpose: Retrieves the learned vocabulary after the adapt() method has been called.

# Returns:
# A list of tokens (words or subwords) in the vocabulary, sorted by frequency in descending order 
# (most frequent tokens appear first).

['',
 '[UNK]',
 'the',
 'to',
 'of',
 'and',
 'a',
 'you',
 'i',
 'is',
 'that',
 'in',
 'it',
 'for',
 'this',
 'not',
 'on',
 'be',
 'as',
 'have',
 'are',
 'your',
 'with',
 'if',
 'article',
 'was',
 'or',
 'but',
 'page',
 'my',
 'an',
 'from',
 'by',
 'do',
 'at',
 'about',
 'me',
 'so',
 'wikipedia',
 'can',
 'what',
 'there',
 'all',
 'has',
 'will',
 'talk',
 'please',
 'would',
 'its',
 'no',
 'one',
 'just',
 'like',
 'they',
 'he',
 'dont',
 'which',
 'any',
 'been',
 'should',
 'more',
 'we',
 'some',
 'other',
 'who',
 'see',
 'here',
 'also',
 'his',
 'think',
 'im',
 'because',
 'know',
 'how',
 'am',
 'people',
 'why',
 'edit',
 'articles',
 'only',
 'out',
 'up',
 'when',
 'were',
 'use',
 'then',
 'may',
 'time',
 'did',
 'them',
 'now',
 'being',
 'their',
 'than',
 'thanks',
 'even',
 'get',
 'make',
 'good',
 'had',
 'very',
 'information',
 'does',
 'could',
 'well',
 'want',
 'such',
 'sources',
 'way',
 'name',
 'these',
 'deletion',
 'pages',
 'first',
 'help'

In [12]:
# Test out tokenizer with random sentence

vectorizer('Hello world, im arian life is good')[:5]

# 'hello' → 288
# 'world' → 263
# 'im' → 70
# 'arian' → 44209   Uncommon or dataset-specific token
# 'life' → 306
# 'is' → 2
# 'good' → 29




print("TensorFlow version:", tf.__version__)
print("Is built with CUDA:", tf.test.is_built_with_cuda())
print("GPUs available:", tf.config.list_physical_devices('GPU'))


TensorFlow version: 2.10.0
Is built with CUDA: False
GPUs available: []


In [13]:
# Tokenize all of our x values
vectorized_text = vectorizer(X.values)

print(vectorized_text)

tf.Tensor(
[[  645    76     2 ...     0     0     0]
 [    1    54  2489 ...     0     0     0]
 [  425   441    70 ...     0     0     0]
 ...
 [32445  7392   383 ...     0     0     0]
 [    5    12   534 ...     0     0     0]
 [    5     8   130 ...     0     0     0]], shape=(159571, 1800), dtype=int64)


# Why use pipeline ?


This approach creates a highly efficient input pipeline:

1- Scalability: Supports large datasets without loading all data into memory at once.

2- Parallelism: Takes advantage of CPU/GPU parallel processing.

3- Performance: Minimizes training bottlenecks by caching, shuffling, batching, and prefetching data ahead of time.

In [15]:
# data pipeline passing our data
# map, chache, shuffle, batch, prefetch  from_tensor_slices, list_file
dataset = tf.data.Dataset.from_tensor_slices((vectorized_text, y)) # input features and y is a target value


dataset = dataset.cache() # Purpose: Caches the dataset in memory or a local file, depending on available resources.
# Benefit: Speeds up the data pipeline by avoiding recomputation or reloading of data for each epoch.

dataset = dataset.shuffle(10000) # Purpose: Randomizes the order of elements in the dataset to prevent training bias.

dataset = dataset.batch(112) # 16 data in each batches 
# Benefit: Allows the model to process multiple data points simultaneously,
# leveraging GPU/TPU parallelism and improving computational efficiency.


dataset = dataset.prefetch(tf.data.AUTOTUNE)
 # Purpose: Ensures that data loading and preprocessing are done asynchronously and ahead of time
# while the model is training on the current batch.
# Benefit: Reduces input pipeline bottlenecks by overlapping data loading with model training.

In [16]:
train = dataset.take(int(len(dataset)*.7))
val = dataset.skip(int(len(dataset)*.7)).take(int(len(dataset)*.2))
test = dataset.skip(int(len(dataset)*.9)).take(int(len(dataset)*.1))

# 2. Create Sequential Model

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Bidirectional, Dense, Embedding

Embeding layer

Purpose: Converting Integer-Encoded Words into Dense Vectors

Why convert words into vectors?

Machine learning models, particularly neural networks, work with numbers rather than words.

Words are first converted into integer indices (e.g., {"the": 1, "cat": 2, "sat": 3}) using techniques like tokenization.

However, integer indices alone don’t provide meaningful representations of the relationships between words.

An Embedding layer maps each integer index to a dense vector of fixed size

============================================================================================


LSTMs are designed to handle sequential data, such as text, audio, or time-series data.

The Bidirectional LSTM ensures that patterns are not missed regardless of whether they appear early or late in the sequence.

Why bidirectional?

Text sequences often have meaning that depends on the context of surrounding words. For example, in the sentence:

"She did not like the movie."

The word "like" depends on the preceding word "not" to convey the correct sentiment.

A Bidirectional LSTM processes the sequence from:

Left to right (forward): Captures dependencies in the order words naturally appear.

Right to left (backward): Captures dependencies looking back at earlier words.

By combining the outputs of the forward and backward LSTMs, the model understands the context from both directions, leading to better feature representations.

The activation function in the LSTM cell is typically tanh for the hidden state because:

tanh squashes values into the range [-1, 1], providing a smooth gradient and preventing extreme values.


===================================================================================================

Dense

Purpose: These layers act as feature extractors to transform the sequence-level features into higher-dimensional spaces.

activation='relu': The Rectified Linear Unit (ReLU) activation introduces non-linearity to the model.

Role: These layers allow the model to learn complex patterns from the temporal features extracted by the Bidirectional LSTM.

====================================================================================================

Final layer

Purpose: Outputs predictions for the target variable(s).


6: Number of output units, corresponding to the 6 classes or labels.

activation='sigmoid': Produces outputs in the range [0, 1], suitable for multi-label classification (where each class can independently be "on" or "off").

Role: Outputs probabilities for each of the 6 labels.



In [18]:
model = Sequential()
# Create the embedding layer 
model.add(Embedding(MAX_WORDS+1, 32))
# Bidirectional LSTM Layer
model.add(Bidirectional(LSTM(32, activation='tanh')))
# Feature extractor Fully connected layers
model.add(Dense(128, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))
# Final layer 
model.add(Dense(6, activation='sigmoid'))

In [19]:
model.compile(loss='BinaryCrossentropy', optimizer='Adam')
# we have got six values coming out of the shouldnt this loss be something line categorical cross entropy ?
# NO we are running six different binary classifires at one time 6 values that are either 0 or 1

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 32)          6400032   
                                                                 
 bidirectional (Bidirectiona  (None, 64)               16640     
 l)                                                              
                                                                 
 dense (Dense)               (None, 128)               8320      
                                                                 
 dense_1 (Dense)             (None, 256)               33024     
                                                                 
 dense_2 (Dense)             (None, 128)               32896     
                                                                 
 dense_3 (Dense)             (None, 6)                 774       
                                                        

# Tools to Decide the Number of Epochs

In [ ]:
# This ensures the model stops training when performance stops improving.

from tensorflow.keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(
    monitor='val_accuracy',  # Monitor validation accuracy
    mode='max',              # Maximize validation accuracy
    patience=3,              # Stop if no improvement after 3 epochs
    restore_best_weights=True  # Restore the best weights after stopping
)

history = model.fit(train, validation_data=val, epochs=10, callbacks=[early_stopping])





# history = model.fit(train, epochs=1, validation_data=val)



In [ ]:
from matplotlib import pyplot as plt

In [ ]:
plt.figure(figsize=(8,5))
pd.DataFrame(history.history).plot()
plt.show()

# 3. Make Predictions

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
# Input text for prediction
input_text = ["You freaking suck! I am going to hit you."]

# Use the vectorizer to tokenize and pad the input text
tokenized_input = vectorizer(input_text)

# Convert to a NumPy array (optional, if your model requires it)
tokenized_input = tokenized_input.numpy()

# Make the prediction
res = model.predict(tokenized_input)
print("Prediction:", res)



In [ ]:
(res > 0.5).astype(int)

In [38]:
batch_X, batch_y = test.as_numpy_iterator().next()

In [39]:
(model.predict(batch_X) > 0.5).astype(int)

4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 116ms/step


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0],
 

In [40]:
res.shape

(1, 6)

# 4. Evaluate Model

In [42]:
from tensorflow.keras.metrics import Precision, Recall, CategoricalAccuracy

In [43]:
pre = Precision()
re = Recall()
acc = CategoricalAccuracy()

In [ ]:
for batch in test.as_numpy_iterator(): 
    # Unpack the batch 
    X_true, y_true = batch
    # Make a prediction 
    yhat = model.predict(X_true)
    
    # Flatten the predictions
    y_true = y_true.flatten()
    yhat = yhat.flatten()
    
    pre.update_state(y_true, yhat)
    re.update_state(y_true, yhat)
    acc.update_state(y_true, yhat)

In [ ]:
print(f'Precision: {pre.result().numpy()}, Recall:{re.result().numpy()}, Accuracy:{acc.result().numpy()}')

# 5. Test and Gradio

In [22]:
!pip install gradio jinja2

  Using cached aiofiles-23.2.1-py3-none-any.whl.metadata (9.7 kB)
  Using cached fastapi-0.115.6-py3-none-any.whl.metadata (27 kB)
  Using cached ffmpy-0.5.0-py3-none-any.whl.metadata (3.0 kB)
  Using cached pydub-0.25.1-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached python_multipart-0.0.20-py3-none-any.whl.metadata (1.8 kB)
  Using cached semantic_version-2.10.0-py2.py3-none-any.whl.metadata (9.7 kB)
  Using cached typer-0.15.1-py3-none-any.whl.metadata (15 kB)
  Using cached uvicorn-0.34.0-py3-none-any.whl.metadata (6.5 kB)
  Using cached starlette-0.41.3-py3-none-any.whl.metadata (6.0 kB)
   ---------------------------------------- 0.0/18.1 MB ? eta -:--:--
    --------------------------------------- 0.3/18.1 MB ? eta -:--:--
   - -------------------------------------- 0.8/18.1 MB 3.0 MB/s eta 0:00:06
   --- ------------------------------------ 1.6/18.1 MB 3.4 MB/s eta 0:00:05
   ----- ---------------------------------- 2.4/18.1 MB 3.4 MB/s eta 0:00:05
   ------ -------------

  You can safely remove it manually.


In [23]:
import tensorflow as tf
import gradio as gr

c:\Users\arian\anaconda3\envs\tf_gpu\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [36]:
model.save('toxicity.h5')

In [37]:
model = tf.keras.models.load_model('toxicity.h5')

In [38]:
input_str = vectorizer('hey i freaken hate you!')

In [39]:
res = model.predict(np.expand_dims(input_str,0))

1/1 [==============================] - 1s 627ms/step


In [40]:
res

array([[0.49944752, 0.4986473 , 0.50177884, 0.4999523 , 0.49915576,
        0.5007688 ]], dtype=float32)

In [ ]:
# Example input
sample_input ="you are stupid"

# Preprocess
tokenized_input = vectorizer([sample_input])

# Predict
prediction = model.predict(tokenized_input)

# Interpret prediction
predicted_labels = (prediction > 0.5).astype(int)
print("Prediction:", predicted_labels[0])


In [ ]:
# Example input
sample_input ="i love you"

# Preprocess
tokenized_input = vectorizer([sample_input])

# Predict
prediction = model.predict(tokenized_input)

# Interpret prediction
predicted_labels = (prediction > 0.5).astype(int)
print("Prediction:", predicted_labels[0])

In [ ]:
class_names = ['class1 : toxic', 'class2 : severe-toxic', 'class3 : obscene', 'class4 : threat', 'class5 : insult', 'class6 : identity hate']

def score_comment(comment):
    # Preprocess the input text using the vectorizer
    tokenized_input = vectorizer([comment])  # vectorizer expects a list of strings
    
    # Make prediction
    prediction = model.predict(tokenized_input)
    
    # Assuming it's a multi-label classification with sigmoid activation
    predicted_labels = (prediction > 0.5).astype(int)[0]
    
    # Map indices to class names
    predicted_classes = [class_names[i] for i, val in enumerate(predicted_labels) if val == 1]
    
    # Create a dictionary for Gradio
    prediction_dict = {cls: 1 for cls in predicted_classes}
    
    return prediction_dict

# Create the Gradio interface
interface = gr.Interface(
    fn=score_comment, 
    inputs=gr.Textbox(lines=2, placeholder='Comment to score'),
    outputs=gr.Label(num_top_classes=6)  # Adjust based on the number of classes
)

# Launch the interface
interface.launch()


Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.


1/1 [==============================] - 0s 71ms/step
